/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as HooksEnrichLoginhistoryGeoRouteImport } from './routes/hooks/enrich-loginhistory-geo'
import { Route as FinanciamentosVeiculosRouteImport } from './routes/financiamentos.veiculos'
import { Route as BackofficeLoginRouteImport } from './routes/backoffice_.login'
import { Route as BackofficeUsuariosRouteImport } from './routes/backoffice.usuarios'
import { Route as BackofficeSegurancaRouteImport } from './routes/backoffice.seguranca'
import { Route as BackofficeRelatoriosRouteImport } from './routes/backoffice.relatorios'
import { Route as BackofficePropostasRouteImport } from './routes/backoffice.propostas'
import { Route as BackofficeDominiosRouteImport } from './routes/backoffice.dominios'
import { Route as BackofficeConfiguracoesRouteImport } from './routes/backoffice.configuracoes'
import { Route as ApiLoginhistoryRouteImport } from './routes/api.loginhistory'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const HooksEnrichLoginhistoryGeoRoute =
  HooksEnrichLoginhistoryGeoRouteImport.update({
    id: '/hooks/enrich-loginhistory-geo',
    path: '/hooks/enrich-loginhistory-geo',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanciamentosVeiculosRoute = FinanciamentosVeiculosRouteImport.update({
  id: '/financiamentos/veiculos',
  path: '/financiamentos/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeLoginRoute = BackofficeLoginRouteImport.update({
  id: '/backoffice_/login',
  path: '/backoffice/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeUsuariosRoute = BackofficeUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeSegurancaRoute = BackofficeSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeRelatoriosRoute = BackofficeRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficePropostasRoute = BackofficePropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDominiosRoute = BackofficeDominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeConfiguracoesRoute = BackofficeConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => BackofficeRoute,
} as any)
const ApiLoginhistoryRoute = ApiLoginhistoryRouteImport.update({
  id: '/api/loginhistory',
  path: '/api/loginhistory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/backoffice/configuracoes': typeof BackofficeConfiguracoesRoute
  '/backoffice/dominios': typeof BackofficeDominiosRoute
  '/backoffice/propostas': typeof BackofficePropostasRoute
  '/backoffice/relatorios': typeof BackofficeRelatoriosRoute
  '/backoffice/seguranca': typeof BackofficeSegurancaRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosRoute
  '/hooks/enrich-loginhistory-geo': typeof HooksEnrichLoginhistoryGeoRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRoute
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/backoffice/configuracoes': typeof BackofficeConfiguracoesRoute
  '/backoffice/dominios': typeof BackofficeDominiosRoute
  '/backoffice/propostas': typeof BackofficePropostasRoute
  '/backoffice/relatorios': typeof BackofficeRelatoriosRoute
  '/backoffice/seguranca': typeof BackofficeSegurancaRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosRoute
  '/hooks/enrich-loginhistory-geo': typeof HooksEnrichLoginhistoryGeoRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/backoffice/configuracoes': typeof BackofficeConfiguracoesRoute
  '/backoffice/dominios': typeof BackofficeDominiosRoute
  '/backoffice/propostas': typeof BackofficePropostasRoute
  '/backoffice/relatorios': typeof BackofficeRelatoriosRoute
  '/backoffice/seguranca': typeof BackofficeSegurancaRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosRoute
  '/backoffice_/login': typeof BackofficeLoginRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosRoute
  '/hooks/enrich-loginhistory-geo': typeof HooksEnrichLoginhistoryGeoRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/sandbox'
    | '/api/loginhistory'
    | '/backoffice/configuracoes'
    | '/backoffice/dominios'
    | '/backoffice/propostas'
    | '/backoffice/relatorios'
    | '/backoffice/seguranca'
    | '/backoffice/usuarios'
    | '/backoffice/login'
    | '/financiamentos/veiculos'
    | '/hooks/enrich-loginhistory-geo'
    | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sandbox'
    | '/api/loginhistory'
    | '/backoffice/configuracoes'
    | '/backoffice/dominios'
    | '/backoffice/propostas'
    | '/backoffice/relatorios'
    | '/backoffice/seguranca'
    | '/backoffice/usuarios'
    | '/backoffice/login'
    | '/financiamentos/veiculos'
    | '/hooks/enrich-loginhistory-geo'
    | '/backoffice'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/sandbox'
    | '/api/loginhistory'
    | '/backoffice/configuracoes'
    | '/backoffice/dominios'
    | '/backoffice/propostas'
    | '/backoffice/relatorios'
    | '/backoffice/seguranca'
    | '/backoffice/usuarios'
    | '/backoffice_/login'
    | '/financiamentos/veiculos'
    | '/hooks/enrich-loginhistory-geo'
    | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  SandboxRoute: typeof SandboxRoute
  ApiLoginhistoryRoute: typeof ApiLoginhistoryRoute
  BackofficeLoginRoute: typeof BackofficeLoginRoute
  FinanciamentosVeiculosRoute: typeof FinanciamentosVeiculosRoute
  HooksEnrichLoginhistoryGeoRoute: typeof HooksEnrichLoginhistoryGeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/hooks/enrich-loginhistory-geo': {
      id: '/hooks/enrich-loginhistory-geo'
      path: '/hooks/enrich-loginhistory-geo'
      fullPath: '/hooks/enrich-loginhistory-geo'
      preLoaderRoute: typeof HooksEnrichLoginhistoryGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos/veiculos': {
      id: '/financiamentos/veiculos'
      path: '/financiamentos/veiculos'
      fullPath: '/financiamentos/veiculos'
      preLoaderRoute: typeof FinanciamentosVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice_/login': {
      id: '/backoffice_/login'
      path: '/backoffice/login'
      fullPath: '/backoffice/login'
      preLoaderRoute: typeof BackofficeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/usuarios': {
      id: '/backoffice/usuarios'
      path: '/usuarios'
      fullPath: '/backoffice/usuarios'
      preLoaderRoute: typeof BackofficeUsuariosRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/seguranca': {
      id: '/backoffice/seguranca'
      path: '/seguranca'
      fullPath: '/backoffice/seguranca'
      preLoaderRoute: typeof BackofficeSegurancaRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/relatorios': {
      id: '/backoffice/relatorios'
      path: '/relatorios'
      fullPath: '/backoffice/relatorios'
      preLoaderRoute: typeof BackofficeRelatoriosRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/propostas': {
      id: '/backoffice/propostas'
      path: '/propostas'
      fullPath: '/backoffice/propostas'
      preLoaderRoute: typeof BackofficePropostasRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/dominios': {
      id: '/backoffice/dominios'
      path: '/dominios'
      fullPath: '/backoffice/dominios'
      preLoaderRoute: typeof BackofficeDominiosRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/configuracoes': {
      id: '/backoffice/configuracoes'
      path: '/configuracoes'
      fullPath: '/backoffice/configuracoes'
      preLoaderRoute: typeof BackofficeConfiguracoesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/api/loginhistory': {
      id: '/api/loginhistory'
      path: '/api/loginhistory'
      fullPath: '/api/loginhistory'
      preLoaderRoute: typeof ApiLoginhistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeConfiguracoesRoute: typeof BackofficeConfiguracoesRoute
  BackofficeDominiosRoute: typeof BackofficeDominiosRoute
  BackofficePropostasRoute: typeof BackofficePropostasRoute
  BackofficeRelatoriosRoute: typeof BackofficeRelatoriosRoute
  BackofficeSegurancaRoute: typeof BackofficeSegurancaRoute
  BackofficeUsuariosRoute: typeof BackofficeUsuariosRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeConfiguracoesRoute: BackofficeConfiguracoesRoute,
  BackofficeDominiosRoute: BackofficeDominiosRoute,
  BackofficePropostasRoute: BackofficePropostasRoute,
  BackofficeRelatoriosRoute: BackofficeRelatoriosRoute,
  BackofficeSegurancaRoute: BackofficeSegurancaRoute,
  BackofficeUsuariosRoute: BackofficeUsuariosRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  SandboxRoute: SandboxRoute,
  ApiLoginhistoryRoute: ApiLoginhistoryRoute,
  BackofficeLoginRoute: BackofficeLoginRoute,
  FinanciamentosVeiculosRoute: FinanciamentosVeiculosRoute,
  HooksEnrichLoginhistoryGeoRoute: HooksEnrichLoginhistoryGeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
