/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinancialGatewayEntryRouteImport } from './routes/financialGatewayEntry'
import { Route as FinancialGatewayGateRouteImport } from './routes/financialGatewayGate'
import { Route as ApiLoginhistoryRouteImport } from './routes/api.loginhistory'

const BackofficeLazyRouteImport = createFileRoute('/backoffice')()
const FinanciamentosLazyRouteImport = createFileRoute('/financiamentos')()
const SandboxLazyRouteImport = createFileRoute('/sandbox')()
const SbxpayLazyRouteImport = createFileRoute('/sbxpay')()
const SegurosLazyRouteImport = createFileRoute('/seguros')()
const AccountsSigninLazyRouteImport = createFileRoute('/accounts/signin')()
const BackofficeIndexLazyRouteImport = createFileRoute('/backoffice/')()
const BackofficeAlertsLazyRouteImport = createFileRoute('/backoffice/alerts')()
const BackofficeAuditLazyRouteImport = createFileRoute('/backoffice/audit')()
const BackofficeConfigsLazyRouteImport = createFileRoute(
  '/backoffice/configs',
)()
const BackofficeConsultsLazyRouteImport = createFileRoute(
  '/backoffice/consults',
)()
const BackofficeDomainsLazyRouteImport = createFileRoute(
  '/backoffice/domains',
)()
const BackofficeReportsLazyRouteImport = createFileRoute(
  '/backoffice/reports',
)()
const BackofficeRoutesLazyRouteImport = createFileRoute('/backoffice/routes')()
const BackofficeSimulationsLazyRouteImport = createFileRoute(
  '/backoffice/simulations',
)()
const BackofficeUsersLazyRouteImport = createFileRoute('/backoffice/users')()
const BackofficeLoginLazyRouteImport = createFileRoute('/backoffice_/login')()
const FinanciamentosAutoEquityLazyRouteImport = createFileRoute(
  '/financiamentos/auto-equity',
)()
const FinanciamentosCartaoLazyRouteImport = createFileRoute(
  '/financiamentos/cartao',
)()
const FinanciamentosSimulacaoLazyRouteImport = createFileRoute(
  '/financiamentos/simulacao',
)()
const FinanciamentosVeiculosLazyRouteImport = createFileRoute(
  '/financiamentos/veiculos',
)()
const SandboxHelpLazyRouteImport = createFileRoute('/sandbox_/help')()
const SbxpayIndexLazyRouteImport = createFileRoute('/sbxpay/')()
const SbxpayOfferLazyRouteImport = createFileRoute('/sbxpay/offer')()
const SegurosAutoLazyRouteImport = createFileRoute('/seguros/auto')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeLazyRoute = BackofficeLazyRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/backoffice.lazy').then((d) => d.Route))
const FinancialGatewayEntryRoute = FinancialGatewayEntryRouteImport.update({
  id: '/financialGatewayEntry',
  path: '/financialGatewayEntry',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialGatewayGateRoute = FinancialGatewayGateRouteImport.update({
  id: '/financialGatewayGate',
  path: '/financialGatewayGate',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentosLazyRoute = FinanciamentosLazyRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/financiamentos.lazy').then((d) => d.Route),
)
const SandboxLazyRoute = SandboxLazyRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sandbox.lazy').then((d) => d.Route))
const SbxpayLazyRoute = SbxpayLazyRouteImport.update({
  id: '/sbxpay',
  path: '/sbxpay',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sbxpay.lazy').then((d) => d.Route))
const SegurosLazyRoute = SegurosLazyRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/seguros.lazy').then((d) => d.Route))
const AccountsSigninLazyRoute = AccountsSigninLazyRouteImport.update({
  id: '/accounts/signin',
  path: '/accounts/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/accounts.signin.lazy').then((d) => d.Route),
)
const ApiLoginhistoryRoute = ApiLoginhistoryRouteImport.update({
  id: '/api/loginhistory',
  path: '/api/loginhistory',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexLazyRoute = BackofficeIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.index.lazy').then((d) => d.Route),
)
const BackofficeAlertsLazyRoute = BackofficeAlertsLazyRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.alerts.lazy').then((d) => d.Route),
)
const BackofficeAuditLazyRoute = BackofficeAuditLazyRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.audit.lazy').then((d) => d.Route),
)
const BackofficeConfigsLazyRoute = BackofficeConfigsLazyRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.configs.lazy').then((d) => d.Route),
)
const BackofficeConsultsLazyRoute = BackofficeConsultsLazyRouteImport.update({
  id: '/consults',
  path: '/consults',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.consults.lazy').then((d) => d.Route),
)
const BackofficeDomainsLazyRoute = BackofficeDomainsLazyRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.domains.lazy').then((d) => d.Route),
)
const BackofficeReportsLazyRoute = BackofficeReportsLazyRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.reports.lazy').then((d) => d.Route),
)
const BackofficeRoutesLazyRoute = BackofficeRoutesLazyRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.routes.lazy').then((d) => d.Route),
)
const BackofficeSimulationsLazyRoute =
  BackofficeSimulationsLazyRouteImport.update({
    id: '/simulations',
    path: '/simulations',
    getParentRoute: () => BackofficeLazyRoute,
  } as any).lazy(() =>
    import('./routes/backoffice.simulations.lazy').then((d) => d.Route),
  )
const BackofficeUsersLazyRoute = BackofficeUsersLazyRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.users.lazy').then((d) => d.Route),
)
const BackofficeLoginLazyRoute = BackofficeLoginLazyRouteImport.update({
  id: '/backoffice_/login',
  path: '/backoffice/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/backoffice_.login.lazy').then((d) => d.Route),
)
const FinanciamentosAutoEquityLazyRoute =
  FinanciamentosAutoEquityLazyRouteImport.update({
    id: '/auto-equity',
    path: '/auto-equity',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.auto-equity.lazy').then((d) => d.Route),
  )
const FinanciamentosCartaoLazyRoute =
  FinanciamentosCartaoLazyRouteImport.update({
    id: '/cartao',
    path: '/cartao',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.cartao.lazy').then((d) => d.Route),
  )
const FinanciamentosSimulacaoLazyRoute =
  FinanciamentosSimulacaoLazyRouteImport.update({
    id: '/simulacao',
    path: '/simulacao',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.simulacao.lazy').then((d) => d.Route),
  )
const FinanciamentosVeiculosLazyRoute =
  FinanciamentosVeiculosLazyRouteImport.update({
    id: '/veiculos',
    path: '/veiculos',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.veiculos.lazy').then((d) => d.Route),
  )
const SandboxHelpLazyRoute = SandboxHelpLazyRouteImport.update({
  id: '/sandbox_/help',
  path: '/sandbox/help',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sandbox_.help.lazy').then((d) => d.Route))
const SbxpayIndexLazyRoute = SbxpayIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SbxpayLazyRoute,
} as any).lazy(() => import('./routes/sbxpay.index.lazy').then((d) => d.Route))
const SbxpayOfferLazyRoute = SbxpayOfferLazyRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => SbxpayLazyRoute,
} as any).lazy(() => import('./routes/sbxpay.offer.lazy').then((d) => d.Route))
const SegurosAutoLazyRoute = SegurosAutoLazyRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => SegurosLazyRoute,
} as any).lazy(() => import('./routes/seguros.auto.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financialGatewayEntry': typeof FinancialGatewayEntryRoute
  '/financialGatewayGate': typeof FinancialGatewayGateRoute
  '/backoffice': typeof BackofficeLazyRouteWithChildren
  '/financiamentos': typeof FinanciamentosLazyRouteWithChildren
  '/sandbox': typeof SandboxLazyRoute
  '/sbxpay': typeof SbxpayLazyRouteWithChildren
  '/seguros': typeof SegurosLazyRouteWithChildren
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/accounts/signin': typeof AccountsSigninLazyRoute
  '/backoffice/alerts': typeof BackofficeAlertsLazyRoute
  '/backoffice/audit': typeof BackofficeAuditLazyRoute
  '/backoffice/configs': typeof BackofficeConfigsLazyRoute
  '/backoffice/consults': typeof BackofficeConsultsLazyRoute
  '/backoffice/domains': typeof BackofficeDomainsLazyRoute
  '/backoffice/reports': typeof BackofficeReportsLazyRoute
  '/backoffice/routes': typeof BackofficeRoutesLazyRoute
  '/backoffice/simulations': typeof BackofficeSimulationsLazyRoute
  '/backoffice/users': typeof BackofficeUsersLazyRoute
  '/backoffice/login': typeof BackofficeLoginLazyRoute
  '/financiamentos/auto-equity': typeof FinanciamentosAutoEquityLazyRoute
  '/financiamentos/cartao': typeof FinanciamentosCartaoLazyRoute
  '/financiamentos/simulacao': typeof FinanciamentosSimulacaoLazyRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosLazyRoute
  '/sandbox/help': typeof SandboxHelpLazyRoute
  '/sbxpay/offer': typeof SbxpayOfferLazyRoute
  '/seguros/auto': typeof SegurosAutoLazyRoute
  '/backoffice/': typeof BackofficeIndexLazyRoute
  '/sbxpay/': typeof SbxpayIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financialGatewayEntry': typeof FinancialGatewayEntryRoute
  '/financialGatewayGate': typeof FinancialGatewayGateRoute
  '/financiamentos': typeof FinanciamentosLazyRouteWithChildren
  '/sandbox': typeof SandboxLazyRoute
  '/seguros': typeof SegurosLazyRouteWithChildren
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/accounts/signin': typeof AccountsSigninLazyRoute
  '/backoffice/alerts': typeof BackofficeAlertsLazyRoute
  '/backoffice/audit': typeof BackofficeAuditLazyRoute
  '/backoffice/configs': typeof BackofficeConfigsLazyRoute
  '/backoffice/consults': typeof BackofficeConsultsLazyRoute
  '/backoffice/domains': typeof BackofficeDomainsLazyRoute
  '/backoffice/reports': typeof BackofficeReportsLazyRoute
  '/backoffice/routes': typeof BackofficeRoutesLazyRoute
  '/backoffice/simulations': typeof BackofficeSimulationsLazyRoute
  '/backoffice/users': typeof BackofficeUsersLazyRoute
  '/backoffice/login': typeof BackofficeLoginLazyRoute
  '/financiamentos/auto-equity': typeof FinanciamentosAutoEquityLazyRoute
  '/financiamentos/cartao': typeof FinanciamentosCartaoLazyRoute
  '/financiamentos/simulacao': typeof FinanciamentosSimulacaoLazyRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosLazyRoute
  '/sandbox/help': typeof SandboxHelpLazyRoute
  '/sbxpay/offer': typeof SbxpayOfferLazyRoute
  '/seguros/auto': typeof SegurosAutoLazyRoute
  '/backoffice': typeof BackofficeIndexLazyRoute
  '/sbxpay': typeof SbxpayIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financialGatewayEntry': typeof FinancialGatewayEntryRoute
  '/financialGatewayGate': typeof FinancialGatewayGateRoute
  '/backoffice': typeof BackofficeLazyRouteWithChildren
  '/financiamentos': typeof FinanciamentosLazyRouteWithChildren
  '/sandbox': typeof SandboxLazyRoute
  '/sbxpay': typeof SbxpayLazyRouteWithChildren
  '/seguros': typeof SegurosLazyRouteWithChildren
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/accounts/signin': typeof AccountsSigninLazyRoute
  '/backoffice/alerts': typeof BackofficeAlertsLazyRoute
  '/backoffice/audit': typeof BackofficeAuditLazyRoute
  '/backoffice/configs': typeof BackofficeConfigsLazyRoute
  '/backoffice/consults': typeof BackofficeConsultsLazyRoute
  '/backoffice/domains': typeof BackofficeDomainsLazyRoute
  '/backoffice/reports': typeof BackofficeReportsLazyRoute
  '/backoffice/routes': typeof BackofficeRoutesLazyRoute
  '/backoffice/simulations': typeof BackofficeSimulationsLazyRoute
  '/backoffice/users': typeof BackofficeUsersLazyRoute
  '/backoffice_/login': typeof BackofficeLoginLazyRoute
  '/financiamentos/auto-equity': typeof FinanciamentosAutoEquityLazyRoute
  '/financiamentos/cartao': typeof FinanciamentosCartaoLazyRoute
  '/financiamentos/simulacao': typeof FinanciamentosSimulacaoLazyRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosLazyRoute
  '/sandbox_/help': typeof SandboxHelpLazyRoute
  '/sbxpay/offer': typeof SbxpayOfferLazyRoute
  '/seguros/auto': typeof SegurosAutoLazyRoute
  '/backoffice/': typeof BackofficeIndexLazyRoute
  '/sbxpay/': typeof SbxpayIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/financialGatewayEntry'
    | '/financialGatewayGate'
    | '/backoffice'
    | '/financiamentos'
    | '/sandbox'
    | '/sbxpay'
    | '/seguros'
    | '/api/loginhistory'
    | '/accounts/signin'
    | '/backoffice/alerts'
    | '/backoffice/audit'
    | '/backoffice/configs'
    | '/backoffice/consults'
    | '/backoffice/domains'
    | '/backoffice/reports'
    | '/backoffice/routes'
    | '/backoffice/simulations'
    | '/backoffice/users'
    | '/backoffice/login'
    | '/financiamentos/auto-equity'
    | '/financiamentos/cartao'
    | '/financiamentos/simulacao'
    | '/financiamentos/veiculos'
    | '/sandbox/help'
    | '/sbxpay/offer'
    | '/seguros/auto'
    | '/backoffice/'
    | '/sbxpay/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financialGatewayEntry'
    | '/financialGatewayGate'
    | '/financiamentos'
    | '/sandbox'
    | '/seguros'
    | '/api/loginhistory'
    | '/accounts/signin'
    | '/backoffice/alerts'
    | '/backoffice/audit'
    | '/backoffice/configs'
    | '/backoffice/consults'
    | '/backoffice/domains'
    | '/backoffice/reports'
    | '/backoffice/routes'
    | '/backoffice/simulations'
    | '/backoffice/users'
    | '/backoffice/login'
    | '/financiamentos/auto-equity'
    | '/financiamentos/cartao'
    | '/financiamentos/simulacao'
    | '/financiamentos/veiculos'
    | '/sandbox/help'
    | '/sbxpay/offer'
    | '/seguros/auto'
    | '/backoffice'
    | '/sbxpay'
  id:
    | '__root__'
    | '/'
    | '/financialGatewayEntry'
    | '/financialGatewayGate'
    | '/backoffice'
    | '/financiamentos'
    | '/sandbox'
    | '/sbxpay'
    | '/seguros'
    | '/api/loginhistory'
    | '/accounts/signin'
    | '/backoffice/alerts'
    | '/backoffice/audit'
    | '/backoffice/configs'
    | '/backoffice/consults'
    | '/backoffice/domains'
    | '/backoffice/reports'
    | '/backoffice/routes'
    | '/backoffice/simulations'
    | '/backoffice/users'
    | '/backoffice_/login'
    | '/financiamentos/auto-equity'
    | '/financiamentos/cartao'
    | '/financiamentos/simulacao'
    | '/financiamentos/veiculos'
    | '/sandbox_/help'
    | '/sbxpay/offer'
    | '/seguros/auto'
    | '/backoffice/'
    | '/sbxpay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancialGatewayEntryRoute: typeof FinancialGatewayEntryRoute
  FinancialGatewayGateRoute: typeof FinancialGatewayGateRoute
  BackofficeLazyRoute: typeof BackofficeLazyRouteWithChildren
  FinanciamentosLazyRoute: typeof FinanciamentosLazyRouteWithChildren
  SandboxLazyRoute: typeof SandboxLazyRoute
  SbxpayLazyRoute: typeof SbxpayLazyRouteWithChildren
  SegurosLazyRoute: typeof SegurosLazyRouteWithChildren
  ApiLoginhistoryRoute: typeof ApiLoginhistoryRoute
  AccountsSigninLazyRoute: typeof AccountsSigninLazyRoute
  BackofficeLoginLazyRoute: typeof BackofficeLoginLazyRoute
  SandboxHelpLazyRoute: typeof SandboxHelpLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financialGatewayEntry': {
      id: '/financialGatewayEntry'
      path: '/financialGatewayEntry'
      fullPath: '/financialGatewayEntry'
      preLoaderRoute: typeof FinancialGatewayEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financialGatewayGate': {
      id: '/financialGatewayGate'
      path: '/financialGatewayGate'
      fullPath: '/financialGatewayGate'
      preLoaderRoute: typeof FinancialGatewayGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos': {
      id: '/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof FinanciamentosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbxpay': {
      id: '/sbxpay'
      path: '/sbxpay'
      fullPath: '/sbxpay'
      preLoaderRoute: typeof SbxpayLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/signin': {
      id: '/accounts/signin'
      path: '/accounts/signin'
      fullPath: '/accounts/signin'
      preLoaderRoute: typeof AccountsSigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loginhistory': {
      id: '/api/loginhistory'
      path: '/api/loginhistory'
      fullPath: '/api/loginhistory'
      preLoaderRoute: typeof ApiLoginhistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/alerts': {
      id: '/backoffice/alerts'
      path: '/alerts'
      fullPath: '/backoffice/alerts'
      preLoaderRoute: typeof BackofficeAlertsLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/audit': {
      id: '/backoffice/audit'
      path: '/audit'
      fullPath: '/backoffice/audit'
      preLoaderRoute: typeof BackofficeAuditLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/configs': {
      id: '/backoffice/configs'
      path: '/configs'
      fullPath: '/backoffice/configs'
      preLoaderRoute: typeof BackofficeConfigsLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/consults': {
      id: '/backoffice/consults'
      path: '/consults'
      fullPath: '/backoffice/consults'
      preLoaderRoute: typeof BackofficeConsultsLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/domains': {
      id: '/backoffice/domains'
      path: '/domains'
      fullPath: '/backoffice/domains'
      preLoaderRoute: typeof BackofficeDomainsLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/reports': {
      id: '/backoffice/reports'
      path: '/reports'
      fullPath: '/backoffice/reports'
      preLoaderRoute: typeof BackofficeReportsLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/routes': {
      id: '/backoffice/routes'
      path: '/routes'
      fullPath: '/backoffice/routes'
      preLoaderRoute: typeof BackofficeRoutesLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/simulations': {
      id: '/backoffice/simulations'
      path: '/simulations'
      fullPath: '/backoffice/simulations'
      preLoaderRoute: typeof BackofficeSimulationsLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/users': {
      id: '/backoffice/users'
      path: '/users'
      fullPath: '/backoffice/users'
      preLoaderRoute: typeof BackofficeUsersLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice_/login': {
      id: '/backoffice_/login'
      path: '/backoffice/login'
      fullPath: '/backoffice/login'
      preLoaderRoute: typeof BackofficeLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos/auto-equity': {
      id: '/financiamentos/auto-equity'
      path: '/auto-equity'
      fullPath: '/financiamentos/auto-equity'
      preLoaderRoute: typeof FinanciamentosAutoEquityLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/financiamentos/cartao': {
      id: '/financiamentos/cartao'
      path: '/cartao'
      fullPath: '/financiamentos/cartao'
      preLoaderRoute: typeof FinanciamentosCartaoLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/financiamentos/simulacao': {
      id: '/financiamentos/simulacao'
      path: '/simulacao'
      fullPath: '/financiamentos/simulacao'
      preLoaderRoute: typeof FinanciamentosSimulacaoLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/financiamentos/veiculos': {
      id: '/financiamentos/veiculos'
      path: '/veiculos'
      fullPath: '/financiamentos/veiculos'
      preLoaderRoute: typeof FinanciamentosVeiculosLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/sandbox_/help': {
      id: '/sandbox_/help'
      path: '/sandbox/help'
      fullPath: '/sandbox/help'
      preLoaderRoute: typeof SandboxHelpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbxpay/': {
      id: '/sbxpay/'
      path: '/'
      fullPath: '/sbxpay/'
      preLoaderRoute: typeof SbxpayIndexLazyRouteImport
      parentRoute: typeof SbxpayLazyRoute
    }
    '/sbxpay/offer': {
      id: '/sbxpay/offer'
      path: '/offer'
      fullPath: '/sbxpay/offer'
      preLoaderRoute: typeof SbxpayOfferLazyRouteImport
      parentRoute: typeof SbxpayLazyRoute
    }
    '/seguros/auto': {
      id: '/seguros/auto'
      path: '/auto'
      fullPath: '/seguros/auto'
      preLoaderRoute: typeof SegurosAutoLazyRouteImport
      parentRoute: typeof SegurosLazyRoute
    }
  }
}

interface BackofficeLazyRouteChildren {
  BackofficeAlertsLazyRoute: typeof BackofficeAlertsLazyRoute
  BackofficeAuditLazyRoute: typeof BackofficeAuditLazyRoute
  BackofficeConfigsLazyRoute: typeof BackofficeConfigsLazyRoute
  BackofficeConsultsLazyRoute: typeof BackofficeConsultsLazyRoute
  BackofficeDomainsLazyRoute: typeof BackofficeDomainsLazyRoute
  BackofficeReportsLazyRoute: typeof BackofficeReportsLazyRoute
  BackofficeRoutesLazyRoute: typeof BackofficeRoutesLazyRoute
  BackofficeSimulationsLazyRoute: typeof BackofficeSimulationsLazyRoute
  BackofficeUsersLazyRoute: typeof BackofficeUsersLazyRoute
  BackofficeIndexLazyRoute: typeof BackofficeIndexLazyRoute
}

const BackofficeLazyRouteChildren: BackofficeLazyRouteChildren = {
  BackofficeAlertsLazyRoute: BackofficeAlertsLazyRoute,
  BackofficeAuditLazyRoute: BackofficeAuditLazyRoute,
  BackofficeConfigsLazyRoute: BackofficeConfigsLazyRoute,
  BackofficeConsultsLazyRoute: BackofficeConsultsLazyRoute,
  BackofficeDomainsLazyRoute: BackofficeDomainsLazyRoute,
  BackofficeReportsLazyRoute: BackofficeReportsLazyRoute,
  BackofficeRoutesLazyRoute: BackofficeRoutesLazyRoute,
  BackofficeSimulationsLazyRoute: BackofficeSimulationsLazyRoute,
  BackofficeUsersLazyRoute: BackofficeUsersLazyRoute,
  BackofficeIndexLazyRoute: BackofficeIndexLazyRoute,
}

const BackofficeLazyRouteWithChildren = BackofficeLazyRoute._addFileChildren(
  BackofficeLazyRouteChildren,
)

interface FinanciamentosLazyRouteChildren {
  FinanciamentosAutoEquityLazyRoute: typeof FinanciamentosAutoEquityLazyRoute
  FinanciamentosCartaoLazyRoute: typeof FinanciamentosCartaoLazyRoute
  FinanciamentosSimulacaoLazyRoute: typeof FinanciamentosSimulacaoLazyRoute
  FinanciamentosVeiculosLazyRoute: typeof FinanciamentosVeiculosLazyRoute
}

const FinanciamentosLazyRouteChildren: FinanciamentosLazyRouteChildren = {
  FinanciamentosAutoEquityLazyRoute: FinanciamentosAutoEquityLazyRoute,
  FinanciamentosCartaoLazyRoute: FinanciamentosCartaoLazyRoute,
  FinanciamentosSimulacaoLazyRoute: FinanciamentosSimulacaoLazyRoute,
  FinanciamentosVeiculosLazyRoute: FinanciamentosVeiculosLazyRoute,
}

const FinanciamentosLazyRouteWithChildren =
  FinanciamentosLazyRoute._addFileChildren(FinanciamentosLazyRouteChildren)

interface SbxpayLazyRouteChildren {
  SbxpayOfferLazyRoute: typeof SbxpayOfferLazyRoute
  SbxpayIndexLazyRoute: typeof SbxpayIndexLazyRoute
}

const SbxpayLazyRouteChildren: SbxpayLazyRouteChildren = {
  SbxpayOfferLazyRoute: SbxpayOfferLazyRoute,
  SbxpayIndexLazyRoute: SbxpayIndexLazyRoute,
}

const SbxpayLazyRouteWithChildren = SbxpayLazyRoute._addFileChildren(
  SbxpayLazyRouteChildren,
)

interface SegurosLazyRouteChildren {
  SegurosAutoLazyRoute: typeof SegurosAutoLazyRoute
}

const SegurosLazyRouteChildren: SegurosLazyRouteChildren = {
  SegurosAutoLazyRoute: SegurosAutoLazyRoute,
}

const SegurosLazyRouteWithChildren = SegurosLazyRoute._addFileChildren(
  SegurosLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancialGatewayEntryRoute: FinancialGatewayEntryRoute,
  FinancialGatewayGateRoute: FinancialGatewayGateRoute,
  BackofficeLazyRoute: BackofficeLazyRouteWithChildren,
  FinanciamentosLazyRoute: FinanciamentosLazyRouteWithChildren,
  SandboxLazyRoute: SandboxLazyRoute,
  SbxpayLazyRoute: SbxpayLazyRouteWithChildren,
  SegurosLazyRoute: SegurosLazyRouteWithChildren,
  ApiLoginhistoryRoute: ApiLoginhistoryRoute,
  AccountsSigninLazyRoute: AccountsSigninLazyRoute,
  BackofficeLoginLazyRoute: BackofficeLoginLazyRoute,
  SandboxHelpLazyRoute: SandboxHelpLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
