/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinancialGatewayEntryRouteImport } from './routes/financialGatewayEntry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLoginhistoryRouteImport } from './routes/api.loginhistory'

const SegurosLazyRouteImport = createFileRoute('/seguros')()
const SbxpayLazyRouteImport = createFileRoute('/sbxpay')()
const FinanciamentosLazyRouteImport = createFileRoute('/financiamentos')()
const BackofficeLazyRouteImport = createFileRoute('/backoffice')()
const SbxpayIndexLazyRouteImport = createFileRoute('/sbxpay/')()
const LandingIndexLazyRouteImport = createFileRoute('/landing/')()
const BackofficeIndexLazyRouteImport = createFileRoute('/backoffice/')()
const SegurosAutoLazyRouteImport = createFileRoute('/seguros/auto')()
const SbxpayOfferLazyRouteImport = createFileRoute('/sbxpay/offer')()
const SbxpayConsultabsxLazyRouteImport = createFileRoute(
  '/sbxpay/consultabsx',
)()
const FinanciamentosVeiculosLazyRouteImport = createFileRoute(
  '/financiamentos/veiculos',
)()
const FinanciamentosSimulacaoLazyRouteImport = createFileRoute(
  '/financiamentos/simulacao',
)()
const FinanciamentosCartaoLazyRouteImport = createFileRoute(
  '/financiamentos/cartao',
)()
const FinanciamentosAutoEquityLazyRouteImport = createFileRoute(
  '/financiamentos/auto-equity',
)()
const BackofficeLoginLazyRouteImport = createFileRoute('/backoffice_/login')()
const BackofficeUsuariosLazyRouteImport = createFileRoute(
  '/backoffice/usuarios',
)()
const BackofficeRelatoriosLazyRouteImport = createFileRoute(
  '/backoffice/relatorios',
)()
const BackofficePropostasLazyRouteImport = createFileRoute(
  '/backoffice/propostas',
)()
const BackofficeDominiosLazyRouteImport = createFileRoute(
  '/backoffice/dominios',
)()
const BackofficeConfiguracoesLazyRouteImport = createFileRoute(
  '/backoffice/configuracoes',
)()
const BackofficeAuditoriaLazyRouteImport = createFileRoute(
  '/backoffice/auditoria',
)()
const AccountsSigninLazyRouteImport = createFileRoute('/accounts/signin')()

const SegurosLazyRoute = SegurosLazyRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/seguros.lazy').then((d) => d.Route))
const SbxpayLazyRoute = SbxpayLazyRouteImport.update({
  id: '/sbxpay',
  path: '/sbxpay',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sbxpay.lazy').then((d) => d.Route))
const FinanciamentosLazyRoute = FinanciamentosLazyRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/financiamentos.lazy').then((d) => d.Route),
)
const BackofficeLazyRoute = BackofficeLazyRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/backoffice.lazy').then((d) => d.Route))
const FinancialGatewayEntryRoute = FinancialGatewayEntryRouteImport.update({
  id: '/financialGatewayEntry',
  path: '/financialGatewayEntry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SbxpayIndexLazyRoute = SbxpayIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SbxpayLazyRoute,
} as any).lazy(() => import('./routes/sbxpay.index.lazy').then((d) => d.Route))
const LandingIndexLazyRoute = LandingIndexLazyRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/landing.index.lazy').then((d) => d.Route))
const BackofficeIndexLazyRoute = BackofficeIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.index.lazy').then((d) => d.Route),
)
const SegurosAutoLazyRoute = SegurosAutoLazyRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => SegurosLazyRoute,
} as any).lazy(() => import('./routes/seguros.auto.lazy').then((d) => d.Route))
const SbxpayOfferLazyRoute = SbxpayOfferLazyRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => SbxpayLazyRoute,
} as any).lazy(() => import('./routes/sbxpay.offer.lazy').then((d) => d.Route))
const SbxpayConsultabsxLazyRoute = SbxpayConsultabsxLazyRouteImport.update({
  id: '/consultabsx',
  path: '/consultabsx',
  getParentRoute: () => SbxpayLazyRoute,
} as any).lazy(() =>
  import('./routes/sbxpay.consultabsx.lazy').then((d) => d.Route),
)
const FinanciamentosVeiculosLazyRoute =
  FinanciamentosVeiculosLazyRouteImport.update({
    id: '/veiculos',
    path: '/veiculos',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.veiculos.lazy').then((d) => d.Route),
  )
const FinanciamentosSimulacaoLazyRoute =
  FinanciamentosSimulacaoLazyRouteImport.update({
    id: '/simulacao',
    path: '/simulacao',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.simulacao.lazy').then((d) => d.Route),
  )
const FinanciamentosCartaoLazyRoute =
  FinanciamentosCartaoLazyRouteImport.update({
    id: '/cartao',
    path: '/cartao',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.cartao.lazy').then((d) => d.Route),
  )
const FinanciamentosAutoEquityLazyRoute =
  FinanciamentosAutoEquityLazyRouteImport.update({
    id: '/auto-equity',
    path: '/auto-equity',
    getParentRoute: () => FinanciamentosLazyRoute,
  } as any).lazy(() =>
    import('./routes/financiamentos.auto-equity.lazy').then((d) => d.Route),
  )
const BackofficeLoginLazyRoute = BackofficeLoginLazyRouteImport.update({
  id: '/backoffice_/login',
  path: '/backoffice/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/backoffice_.login.lazy').then((d) => d.Route),
)
const BackofficeUsuariosLazyRoute = BackofficeUsuariosLazyRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.usuarios.lazy').then((d) => d.Route),
)
const BackofficeRelatoriosLazyRoute =
  BackofficeRelatoriosLazyRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => BackofficeLazyRoute,
  } as any).lazy(() =>
    import('./routes/backoffice.relatorios.lazy').then((d) => d.Route),
  )
const BackofficePropostasLazyRoute = BackofficePropostasLazyRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.propostas.lazy').then((d) => d.Route),
)
const BackofficeDominiosLazyRoute = BackofficeDominiosLazyRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.dominios.lazy').then((d) => d.Route),
)
const BackofficeConfiguracoesLazyRoute =
  BackofficeConfiguracoesLazyRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => BackofficeLazyRoute,
  } as any).lazy(() =>
    import('./routes/backoffice.configuracoes.lazy').then((d) => d.Route),
  )
const BackofficeAuditoriaLazyRoute = BackofficeAuditoriaLazyRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => BackofficeLazyRoute,
} as any).lazy(() =>
  import('./routes/backoffice.auditoria.lazy').then((d) => d.Route),
)
const AccountsSigninLazyRoute = AccountsSigninLazyRouteImport.update({
  id: '/accounts/signin',
  path: '/accounts/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/accounts.signin.lazy').then((d) => d.Route),
)
const ApiLoginhistoryRoute = ApiLoginhistoryRouteImport.update({
  id: '/api/loginhistory',
  path: '/api/loginhistory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financialGatewayEntry': typeof FinancialGatewayEntryRoute
  '/backoffice': typeof BackofficeLazyRouteWithChildren
  '/financiamentos': typeof FinanciamentosLazyRouteWithChildren
  '/sbxpay': typeof SbxpayLazyRouteWithChildren
  '/seguros': typeof SegurosLazyRouteWithChildren
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/accounts/signin': typeof AccountsSigninLazyRoute
  '/backoffice/auditoria': typeof BackofficeAuditoriaLazyRoute
  '/backoffice/configuracoes': typeof BackofficeConfiguracoesLazyRoute
  '/backoffice/dominios': typeof BackofficeDominiosLazyRoute
  '/backoffice/propostas': typeof BackofficePropostasLazyRoute
  '/backoffice/relatorios': typeof BackofficeRelatoriosLazyRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosLazyRoute
  '/backoffice/login': typeof BackofficeLoginLazyRoute
  '/financiamentos/auto-equity': typeof FinanciamentosAutoEquityLazyRoute
  '/financiamentos/cartao': typeof FinanciamentosCartaoLazyRoute
  '/financiamentos/simulacao': typeof FinanciamentosSimulacaoLazyRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosLazyRoute
  '/sbxpay/consultabsx': typeof SbxpayConsultabsxLazyRoute
  '/sbxpay/offer': typeof SbxpayOfferLazyRoute
  '/seguros/auto': typeof SegurosAutoLazyRoute
  '/backoffice/': typeof BackofficeIndexLazyRoute
  '/landing/': typeof LandingIndexLazyRoute
  '/sbxpay/': typeof SbxpayIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financialGatewayEntry': typeof FinancialGatewayEntryRoute
  '/financiamentos': typeof FinanciamentosLazyRouteWithChildren
  '/seguros': typeof SegurosLazyRouteWithChildren
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/accounts/signin': typeof AccountsSigninLazyRoute
  '/backoffice/auditoria': typeof BackofficeAuditoriaLazyRoute
  '/backoffice/configuracoes': typeof BackofficeConfiguracoesLazyRoute
  '/backoffice/dominios': typeof BackofficeDominiosLazyRoute
  '/backoffice/propostas': typeof BackofficePropostasLazyRoute
  '/backoffice/relatorios': typeof BackofficeRelatoriosLazyRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosLazyRoute
  '/backoffice/login': typeof BackofficeLoginLazyRoute
  '/financiamentos/auto-equity': typeof FinanciamentosAutoEquityLazyRoute
  '/financiamentos/cartao': typeof FinanciamentosCartaoLazyRoute
  '/financiamentos/simulacao': typeof FinanciamentosSimulacaoLazyRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosLazyRoute
  '/sbxpay/consultabsx': typeof SbxpayConsultabsxLazyRoute
  '/sbxpay/offer': typeof SbxpayOfferLazyRoute
  '/seguros/auto': typeof SegurosAutoLazyRoute
  '/backoffice': typeof BackofficeIndexLazyRoute
  '/landing': typeof LandingIndexLazyRoute
  '/sbxpay': typeof SbxpayIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financialGatewayEntry': typeof FinancialGatewayEntryRoute
  '/backoffice': typeof BackofficeLazyRouteWithChildren
  '/financiamentos': typeof FinanciamentosLazyRouteWithChildren
  '/sbxpay': typeof SbxpayLazyRouteWithChildren
  '/seguros': typeof SegurosLazyRouteWithChildren
  '/api/loginhistory': typeof ApiLoginhistoryRoute
  '/accounts/signin': typeof AccountsSigninLazyRoute
  '/backoffice/auditoria': typeof BackofficeAuditoriaLazyRoute
  '/backoffice/configuracoes': typeof BackofficeConfiguracoesLazyRoute
  '/backoffice/dominios': typeof BackofficeDominiosLazyRoute
  '/backoffice/propostas': typeof BackofficePropostasLazyRoute
  '/backoffice/relatorios': typeof BackofficeRelatoriosLazyRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosLazyRoute
  '/backoffice_/login': typeof BackofficeLoginLazyRoute
  '/financiamentos/auto-equity': typeof FinanciamentosAutoEquityLazyRoute
  '/financiamentos/cartao': typeof FinanciamentosCartaoLazyRoute
  '/financiamentos/simulacao': typeof FinanciamentosSimulacaoLazyRoute
  '/financiamentos/veiculos': typeof FinanciamentosVeiculosLazyRoute
  '/sbxpay/consultabsx': typeof SbxpayConsultabsxLazyRoute
  '/sbxpay/offer': typeof SbxpayOfferLazyRoute
  '/seguros/auto': typeof SegurosAutoLazyRoute
  '/backoffice/': typeof BackofficeIndexLazyRoute
  '/landing/': typeof LandingIndexLazyRoute
  '/sbxpay/': typeof SbxpayIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/financialGatewayEntry'
    | '/backoffice'
    | '/financiamentos'
    | '/sbxpay'
    | '/seguros'
    | '/api/loginhistory'
    | '/accounts/signin'
    | '/backoffice/auditoria'
    | '/backoffice/configuracoes'
    | '/backoffice/dominios'
    | '/backoffice/propostas'
    | '/backoffice/relatorios'
    | '/backoffice/usuarios'
    | '/backoffice/login'
    | '/financiamentos/auto-equity'
    | '/financiamentos/cartao'
    | '/financiamentos/simulacao'
    | '/financiamentos/veiculos'
    | '/sbxpay/consultabsx'
    | '/sbxpay/offer'
    | '/seguros/auto'
    | '/backoffice/'
    | '/landing/'
    | '/sbxpay/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financialGatewayEntry'
    | '/financiamentos'
    | '/seguros'
    | '/api/loginhistory'
    | '/accounts/signin'
    | '/backoffice/auditoria'
    | '/backoffice/configuracoes'
    | '/backoffice/dominios'
    | '/backoffice/propostas'
    | '/backoffice/relatorios'
    | '/backoffice/usuarios'
    | '/backoffice/login'
    | '/financiamentos/auto-equity'
    | '/financiamentos/cartao'
    | '/financiamentos/simulacao'
    | '/financiamentos/veiculos'
    | '/sbxpay/consultabsx'
    | '/sbxpay/offer'
    | '/seguros/auto'
    | '/backoffice'
    | '/landing'
    | '/sbxpay'
  id:
    | '__root__'
    | '/'
    | '/financialGatewayEntry'
    | '/backoffice'
    | '/financiamentos'
    | '/sbxpay'
    | '/seguros'
    | '/api/loginhistory'
    | '/accounts/signin'
    | '/backoffice/auditoria'
    | '/backoffice/configuracoes'
    | '/backoffice/dominios'
    | '/backoffice/propostas'
    | '/backoffice/relatorios'
    | '/backoffice/usuarios'
    | '/backoffice_/login'
    | '/financiamentos/auto-equity'
    | '/financiamentos/cartao'
    | '/financiamentos/simulacao'
    | '/financiamentos/veiculos'
    | '/sbxpay/consultabsx'
    | '/sbxpay/offer'
    | '/seguros/auto'
    | '/backoffice/'
    | '/landing/'
    | '/sbxpay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancialGatewayEntryRoute: typeof FinancialGatewayEntryRoute
  BackofficeLazyRoute: typeof BackofficeLazyRouteWithChildren
  FinanciamentosLazyRoute: typeof FinanciamentosLazyRouteWithChildren
  SbxpayLazyRoute: typeof SbxpayLazyRouteWithChildren
  SegurosLazyRoute: typeof SegurosLazyRouteWithChildren
  ApiLoginhistoryRoute: typeof ApiLoginhistoryRoute
  AccountsSigninLazyRoute: typeof AccountsSigninLazyRoute
  BackofficeLoginLazyRoute: typeof BackofficeLoginLazyRoute
  LandingIndexLazyRoute: typeof LandingIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbxpay': {
      id: '/sbxpay'
      path: '/sbxpay'
      fullPath: '/sbxpay'
      preLoaderRoute: typeof SbxpayLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos': {
      id: '/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof FinanciamentosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financialGatewayEntry': {
      id: '/financialGatewayEntry'
      path: '/financialGatewayEntry'
      fullPath: '/financialGatewayEntry'
      preLoaderRoute: typeof FinancialGatewayEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbxpay/': {
      id: '/sbxpay/'
      path: '/'
      fullPath: '/sbxpay/'
      preLoaderRoute: typeof SbxpayIndexLazyRouteImport
      parentRoute: typeof SbxpayLazyRoute
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/seguros/auto': {
      id: '/seguros/auto'
      path: '/auto'
      fullPath: '/seguros/auto'
      preLoaderRoute: typeof SegurosAutoLazyRouteImport
      parentRoute: typeof SegurosLazyRoute
    }
    '/sbxpay/offer': {
      id: '/sbxpay/offer'
      path: '/offer'
      fullPath: '/sbxpay/offer'
      preLoaderRoute: typeof SbxpayOfferLazyRouteImport
      parentRoute: typeof SbxpayLazyRoute
    }
    '/sbxpay/consultabsx': {
      id: '/sbxpay/consultabsx'
      path: '/consultabsx'
      fullPath: '/sbxpay/consultabsx'
      preLoaderRoute: typeof SbxpayConsultabsxLazyRouteImport
      parentRoute: typeof SbxpayLazyRoute
    }
    '/financiamentos/veiculos': {
      id: '/financiamentos/veiculos'
      path: '/veiculos'
      fullPath: '/financiamentos/veiculos'
      preLoaderRoute: typeof FinanciamentosVeiculosLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/financiamentos/simulacao': {
      id: '/financiamentos/simulacao'
      path: '/simulacao'
      fullPath: '/financiamentos/simulacao'
      preLoaderRoute: typeof FinanciamentosSimulacaoLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/financiamentos/cartao': {
      id: '/financiamentos/cartao'
      path: '/cartao'
      fullPath: '/financiamentos/cartao'
      preLoaderRoute: typeof FinanciamentosCartaoLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/financiamentos/auto-equity': {
      id: '/financiamentos/auto-equity'
      path: '/auto-equity'
      fullPath: '/financiamentos/auto-equity'
      preLoaderRoute: typeof FinanciamentosAutoEquityLazyRouteImport
      parentRoute: typeof FinanciamentosLazyRoute
    }
    '/backoffice_/login': {
      id: '/backoffice_/login'
      path: '/backoffice/login'
      fullPath: '/backoffice/login'
      preLoaderRoute: typeof BackofficeLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/usuarios': {
      id: '/backoffice/usuarios'
      path: '/usuarios'
      fullPath: '/backoffice/usuarios'
      preLoaderRoute: typeof BackofficeUsuariosLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/relatorios': {
      id: '/backoffice/relatorios'
      path: '/relatorios'
      fullPath: '/backoffice/relatorios'
      preLoaderRoute: typeof BackofficeRelatoriosLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/propostas': {
      id: '/backoffice/propostas'
      path: '/propostas'
      fullPath: '/backoffice/propostas'
      preLoaderRoute: typeof BackofficePropostasLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/dominios': {
      id: '/backoffice/dominios'
      path: '/dominios'
      fullPath: '/backoffice/dominios'
      preLoaderRoute: typeof BackofficeDominiosLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/configuracoes': {
      id: '/backoffice/configuracoes'
      path: '/configuracoes'
      fullPath: '/backoffice/configuracoes'
      preLoaderRoute: typeof BackofficeConfiguracoesLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/backoffice/auditoria': {
      id: '/backoffice/auditoria'
      path: '/auditoria'
      fullPath: '/backoffice/auditoria'
      preLoaderRoute: typeof BackofficeAuditoriaLazyRouteImport
      parentRoute: typeof BackofficeLazyRoute
    }
    '/accounts/signin': {
      id: '/accounts/signin'
      path: '/accounts/signin'
      fullPath: '/accounts/signin'
      preLoaderRoute: typeof AccountsSigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loginhistory': {
      id: '/api/loginhistory'
      path: '/api/loginhistory'
      fullPath: '/api/loginhistory'
      preLoaderRoute: typeof ApiLoginhistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackofficeLazyRouteChildren {
  BackofficeAuditoriaLazyRoute: typeof BackofficeAuditoriaLazyRoute
  BackofficeConfiguracoesLazyRoute: typeof BackofficeConfiguracoesLazyRoute
  BackofficeDominiosLazyRoute: typeof BackofficeDominiosLazyRoute
  BackofficePropostasLazyRoute: typeof BackofficePropostasLazyRoute
  BackofficeRelatoriosLazyRoute: typeof BackofficeRelatoriosLazyRoute
  BackofficeUsuariosLazyRoute: typeof BackofficeUsuariosLazyRoute
  BackofficeIndexLazyRoute: typeof BackofficeIndexLazyRoute
}

const BackofficeLazyRouteChildren: BackofficeLazyRouteChildren = {
  BackofficeAuditoriaLazyRoute: BackofficeAuditoriaLazyRoute,
  BackofficeConfiguracoesLazyRoute: BackofficeConfiguracoesLazyRoute,
  BackofficeDominiosLazyRoute: BackofficeDominiosLazyRoute,
  BackofficePropostasLazyRoute: BackofficePropostasLazyRoute,
  BackofficeRelatoriosLazyRoute: BackofficeRelatoriosLazyRoute,
  BackofficeUsuariosLazyRoute: BackofficeUsuariosLazyRoute,
  BackofficeIndexLazyRoute: BackofficeIndexLazyRoute,
}

const BackofficeLazyRouteWithChildren = BackofficeLazyRoute._addFileChildren(
  BackofficeLazyRouteChildren,
)

interface FinanciamentosLazyRouteChildren {
  FinanciamentosAutoEquityLazyRoute: typeof FinanciamentosAutoEquityLazyRoute
  FinanciamentosCartaoLazyRoute: typeof FinanciamentosCartaoLazyRoute
  FinanciamentosSimulacaoLazyRoute: typeof FinanciamentosSimulacaoLazyRoute
  FinanciamentosVeiculosLazyRoute: typeof FinanciamentosVeiculosLazyRoute
}

const FinanciamentosLazyRouteChildren: FinanciamentosLazyRouteChildren = {
  FinanciamentosAutoEquityLazyRoute: FinanciamentosAutoEquityLazyRoute,
  FinanciamentosCartaoLazyRoute: FinanciamentosCartaoLazyRoute,
  FinanciamentosSimulacaoLazyRoute: FinanciamentosSimulacaoLazyRoute,
  FinanciamentosVeiculosLazyRoute: FinanciamentosVeiculosLazyRoute,
}

const FinanciamentosLazyRouteWithChildren =
  FinanciamentosLazyRoute._addFileChildren(FinanciamentosLazyRouteChildren)

interface SbxpayLazyRouteChildren {
  SbxpayConsultabsxLazyRoute: typeof SbxpayConsultabsxLazyRoute
  SbxpayOfferLazyRoute: typeof SbxpayOfferLazyRoute
  SbxpayIndexLazyRoute: typeof SbxpayIndexLazyRoute
}

const SbxpayLazyRouteChildren: SbxpayLazyRouteChildren = {
  SbxpayConsultabsxLazyRoute: SbxpayConsultabsxLazyRoute,
  SbxpayOfferLazyRoute: SbxpayOfferLazyRoute,
  SbxpayIndexLazyRoute: SbxpayIndexLazyRoute,
}

const SbxpayLazyRouteWithChildren = SbxpayLazyRoute._addFileChildren(
  SbxpayLazyRouteChildren,
)

interface SegurosLazyRouteChildren {
  SegurosAutoLazyRoute: typeof SegurosAutoLazyRoute
}

const SegurosLazyRouteChildren: SegurosLazyRouteChildren = {
  SegurosAutoLazyRoute: SegurosAutoLazyRoute,
}

const SegurosLazyRouteWithChildren = SegurosLazyRoute._addFileChildren(
  SegurosLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancialGatewayEntryRoute: FinancialGatewayEntryRoute,
  BackofficeLazyRoute: BackofficeLazyRouteWithChildren,
  FinanciamentosLazyRoute: FinanciamentosLazyRouteWithChildren,
  SbxpayLazyRoute: SbxpayLazyRouteWithChildren,
  SegurosLazyRoute: SegurosLazyRouteWithChildren,
  ApiLoginhistoryRoute: ApiLoginhistoryRoute,
  AccountsSigninLazyRoute: AccountsSigninLazyRoute,
  BackofficeLoginLazyRoute: BackofficeLoginLazyRoute,
  LandingIndexLazyRoute: LandingIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
