// Custom server-side Supabase admin client pointing to the user's own Supabase project.
// This file is intentionally NOT auto-generated by Lovable, so credentials stick across regenerations.
// Set MY_SUPABASE_URL and MY_SUPABASE_SERVICE_ROLE_KEY in your server env (wrangler.jsonc / .dev.vars).
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

function createCustomAdminClient(): SupabaseClient {
  const url = process.env.MY_SUPABASE_URL;
  const serviceRoleKey = process.env.MY_SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !serviceRoleKey) {
    throw new Error(
      "Missing custom Supabase env vars. Set MY_SUPABASE_URL and MY_SUPABASE_SERVICE_ROLE_KEY.",
    );
  }

  return createClient(url, serviceRoleKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _client: SupabaseClient | undefined;

export const customSupabaseAdmin = new Proxy({} as SupabaseClient, {
  get(_, prop, receiver) {
    if (!_client) _client = createCustomAdminClient();
    return Reflect.get(_client, prop, receiver);
  },
});
